baseURL = "https://github.com/javadsajjadi/ibook/"
languageCode = 'fa'
title = 'کتابفروشی قلم من'
contentdir          = "content"
layoutdir           = "layouts"
publishDir          = "docs"
author              = "Qezwan"
title               = "Qezwan"


[pagination]
pagerSize = 6

[params]
    dateFormat = 'jan 2, 2006'


[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
